# 🎯 Elite Poker AI Configuration
# Complete NLHE 6-max configuration for professional-grade training

# Game Engine Configuration
game_engine:
  num_players: 6
  small_blind: 1.0
  big_blind: 2.0
  starting_stack: 100.0
  max_actions_per_game: 100

# Training Configuration
training:
  batch_size: 32768  # H100 optimized
  learning_rate: 0.05
  temperature: 1.0
  num_iterations: 100000
  save_interval: 1000
  
# Bucketing Configuration
bucketing:
  num_buckets: 500000  # Elite target
  bucket_config:
    hand_strength: 1000
    position: 6
    stack_depth: 20
    pot_ratio: 15
    betting_history: 10
  
# Memory Configuration
memory:
  max_info_sets: 500000
  growth_factor: 1.5
  chunk_size: 20000
  
# Performance Configuration
performance:
  use_gpu: true
  use_jit: true
  use_vectorization: true
  device_preference: "gpu"
  
# Validation Configuration
validation:
  test_games: 1000
  zero_sum_tolerance: 0.001
  min_performance_gps: 100  # Games per second
  
# Output Configuration
output:
  save_path: "models/elite_poker_ai"
  log_level: "INFO"
  checkpoint_format: "pickle"